{
 "title": "Disponibilidade Geral",
 "tags": [ "disponibilidade" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Qtd. Sistemas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DATEDIFF(second, '1970-01-01', getdate()) AS time,\n  count(1) as value,\n  'Qtd Operadoras' as metric\nFROM\n  Sistema S\nJOIN\n  Ambiente A on A.handle = S.HandleAmbiente\nWHERE 1=1\n  --(A.Nome = '$Ambiente' or '$Ambiente' = '** TODOS **')\n  \n\n"
    }
   ]
  },
  {
   "title": "Duração Média do Ping (ms)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DATEDIFF(second, '1970-01-01', getdate()) AS time,\n  avg(c.DuracaoMilisegundosRequisicao) as value,\n  'Duração Média' as metric\nFROM\n  WebServiceCheck C\nJOIN\n  Ambiente A on a.Handle = c.HandleAmbiente\nWHERE\n  $__timeFilter(c.DataHoraBateriaTestes) \n  --and (A.Nome = '$Ambiente' or '$Ambiente' = '** TODOS **')\n  and C.DuracaoMilisegundosRequisicao is not null\n\n"
    }
   ]
  },
  {
   "title": "Disponibilidade Geral dos Serviços por Sistema",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeEpoch(H.DataHoraStatus),\r\n  (2-H.Status) as value,\r\n  A.Nome + ' - ' + S.Nome as metric\r\nFROM\r\n  WebServiceHealth H\r\nJOIN \r\n  Sistema S on S.Handle = H.HandleSistema\r\nJOIN\r\n  Ambiente A on A.Handle = H.HandleAmbiente  \r\nWHERE\r\n  $__timeFilter(H.DataHoraStatus) \r\n  --and (A.Nome = '$Ambiente' or '$Ambiente' = '** TODOS **')\r\n  and H.NomeServicoIntegracao is null\r\nORDER BY\r\n  A.Nome ASC, S.Nome ASC"
    }
   ]
  },
  {
   "title": "Qtd. de Serviços por Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n  X.time,\r\n  SUM(X.value) AS VALUE,\r\n  x.metric\r\nfrom (\r\nSELECT\r\n  $__timeEpoch(C.DataHoraBateriaTestes),\r\n  count(1) as value,\r\n  'Sucesso' as metric\r\nFROM\r\n  WebServiceCheck C\r\nJOIN \r\n  Sistema S on S.Handle = C.HandleSistema\r\nJOIN \r\n  Ambiente A on A.Handle = C.HandleAmbiente  \r\nWHERE\r\n  $__timeFilter(C.DataHoraBateriaTestes)\r\n  --and (A.Nome = '$Ambiente' or '$Ambiente' = '** TODOS **')\r\n  and C.Url is not null\r\n  and ISNULL(C.HttpStatusResposta, 0) = 200\r\nGROUP BY C.DataHoraBateriaTestes\r\nUNION\r\nSELECT\r\n  $__timeEpoch(C.DataHoraBateriaTestes),\r\n  0 as value,\r\n  'Sucesso' as metric\r\nFROM\r\n  WebServiceCheck C\r\nJOIN \r\n  Sistema S on S.Handle = C.HandleSistema\r\nJOIN \r\n  Ambiente A on A.Handle = C.HandleAmbiente\r\nWHERE\r\n  $__timeFilter(C.DataHoraBateriaTestes)\r\n  --and (A.Nome = '$Ambiente' or '$Ambiente' = '** TODOS **')\r\n  and C.Url is not null\r\n  and ISNULL(C.HttpStatusResposta, 0) != 200\r\nGROUP BY C.DataHoraBateriaTestes\r\n) x\r\nGROUP BY X.TIME, X.METRIC\r\nORDER BY\r\n  1 ASC"
    },
    {
     "rawSql": "SELECT \r\n  X.time,\r\n  SUM(X.value) AS VALUE,\r\n  x.metric\r\nfrom (\r\nSELECT\r\n  $__timeEpoch(C.DataHoraBateriaTestes),\r\n  count(1) as value,\r\n  'Erro' as metric\r\nFROM\r\n  WebServiceCheck C\r\nJOIN \r\n  Sistema S on S.Handle = C.HandleSistema\r\nJOIN \r\n  Ambiente A on A.Handle = C.HandleAmbiente  \r\nWHERE\r\n  $__timeFilter(C.DataHoraBateriaTestes)\r\n  --and (A.Nome = '$Ambiente' or '$Ambiente' = '** TODOS **')\r\n  and C.Url is not null\r\n  and ISNULL(C.HttpStatusResposta, 0) != 200\r\nGROUP BY C.DataHoraBateriaTestes\r\nUNION\r\nSELECT\r\n  $__timeEpoch(C.DataHoraBateriaTestes),\r\n  0 as value,\r\n  'Erro' as metric\r\nFROM\r\n  WebServiceCheck C\r\nJOIN \r\n  Sistema S on S.Handle = C.HandleSistema\r\nJOIN \r\n  Ambiente A on A.Handle = C.HandleAmbiente\r\nWHERE\r\n  $__timeFilter(C.DataHoraBateriaTestes)\r\n  --and (A.Nome = '$Ambiente' or '$Ambiente' = '** TODOS **')\r\n  and C.Url is not null\r\n  and (ISNULL(C.HttpStatusResposta, 0) = 200)\r\nGROUP BY C.DataHoraBateriaTestes\r\n) x\r\nGROUP BY X.time, X.metric\r\nORDER BY\r\n  1 ASC"
    }
   ]
  },
  {
   "title": "Alertas",
   "type": "alertlist",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch(<time_column>),\n  <value column> as value,\n  <series name column> as metric\nFROM\n  <table name>\nWHERE\n  $__timeFilter(time_column)\nORDER BY\n  <time_column> ASC"
    }
   ]
  }
 ]
}