{
 "title": "Disponibilidade por Ambiente",
 "tags": [ "disponibilidade" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Ambiente", "query": "SELECT Nome FROM Ambiente" }
  ]
 },
 "panels": [
  {
   "title": "Qtd. Sistemas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DATEDIFF(second, '1970-01-01', getdate()) AS time,\n  count(1) as value,\n  'Qtd Operadoras' as metric\nFROM\n  Sistema S\nJOIN\n  Ambiente A on A.handle = S.HandleAmbiente\nWHERE \n  A.Nome = '$Ambiente'\n  \n\n"
    }
   ]
  },
  {
   "title": "Duração Média do Ping (ms)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  DATEDIFF(second, '1970-01-01', getdate()) AS time,\n  avg(c.DuracaoMilisegundosRequisicao) as value,\n  'Duração Média' as metric\nFROM\n  WebServiceCheck C\nJOIN\n  Ambiente A on a.Handle = c.HandleAmbiente\nWHERE\n  $__timeFilter(c.DataHoraBateriaTestes) \n  and A.Nome = '$Ambiente'\n  and C.DuracaoMilisegundosRequisicao is not null\n\n"
    }
   ]
  },
  {
   "title": "Disponibilidade Geral dos Serviços por Sistema",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeEpoch(H.DataHoraStatus),\r\n  (2-H.Status) as value,\r\n  S.Nome as metric\r\nFROM\r\n  WebServiceHealth H\r\nJOIN \r\n  Sistema S on S.Handle = H.HandleSistema\r\nJOIN\r\n  Ambiente A on A.Handle = H.HandleAmbiente  \r\nWHERE\r\n  $__timeFilter(H.DataHoraStatus) \r\n  and A.Nome = '$Ambiente'\r\n  and H.NomeServicoIntegracao is null\r\nORDER BY\r\n  S.Nome ASC"
    }
   ]
  }
 ]
}