{
 "title": "Disponibilidade por Sistema",
 "tags": [ "disponibilidade" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Ambiente", "query": "SELECT Nome FROM Ambiente" },
   {
    "name": "Sistema",
    "query": "SELECT S.NOME\nFROM SISTEMA S\nJOIN AMBIENTE A ON A.HANDLE  = S.HANDLEAMBIENTE\nWHERE A.NOME = '$Ambiente'"
   }
  ]
 },
 "panels": [
  {
   "title": "Disponibilidade Geral do Sistema",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeEpoch(H.DataHoraStatus),\r\n  (2-H.Status) as value,\r\n  LTRIM(STR(H.QuantidadeWebServices,2))+' Serviços' as metric\r\nFROM\r\n  WebServiceHealth H\r\nJOIN \r\n  Sistema S on S.Handle = H.HandleSistema\r\nJOIN\r\n  Ambiente A on A.Handle = H.HandleAmbiente  \r\nWHERE\r\n  $__timeFilter(H.DataHoraStatus) \r\n  and S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\n  and H.Url is null\r\nORDER BY\r\n  H.DataHoraStatus ASC"
    }
   ]
  },
  {
   "title": "Disponibilidade por Serviço",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeEpoch(H.DataHoraStatus),\r\n  (2-H.Status) as value,\r\n  H.NomeServicoIntegracao as metric\r\nFROM\r\n  WebServiceHealth H\r\nJOIN \r\n  Sistema S on S.Handle = H.HandleSistema\r\nJOIN\r\n  Ambiente A on A.Handle = H.HandleAmbiente  \r\nWHERE\r\n  $__timeFilter(H.DataHoraStatus) \r\n  and S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\n  and H.NomeServicoIntegracao is not null\r\nORDER BY\r\n  H.DataHoraStatus ASC, H.NomeServicoIntegracao ASC"
    }
   ]
  },
  {
   "title": "Tempo Resposta do Ping por Servço",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Milissegundos" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch(H.DataHoraStatus),\n  H.TempoMediaResposta as value,\n  H.NOMESERVICOINTEGRACAO as metric\nFROM\n  WebServiceHealth H\nJOIN \n  Sistema S on S.Handle = H.HandleSistema\nJOIN\n  Ambiente A on A.Handle = H.HandleAmbiente\nWHERE\n  $__timeFilter(H.DataHoraStatus) \n  and S.Nome = '$Sistema' \n  and A.Nome = '$Ambiente'\n  and H.Url is not null\n  and H.TempoMediaResposta is not null\nORDER BY\n  H.DataHoraStatus ASC"
    }
   ]
  },
  {
   "title": "Qtd. de Serviços por Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n  X.time,\r\n  SUM(X.value) AS VALUE,\r\n  x.metric\r\nfrom (\r\nSELECT\r\n  $__timeEpoch(C.DataHoraBateriaTestes),\r\n  count(1) as value,\r\n  'Sucesso' as metric\r\nFROM\r\n  WebServiceCheck C\r\nJOIN \r\n  Sistema S on S.Handle = C.HandleSistema\r\nJOIN \r\n  Ambiente A on A.Handle = C.HandleAmbiente  \r\nWHERE\r\n  $__timeFilter(C.DataHoraBateriaTestes)\r\n  and S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\n  and C.Url is not null\r\n  and ISNULL(C.HttpStatusResposta, 0) = 200\r\nGROUP BY C.DataHoraBateriaTestes\r\nUNION\r\nSELECT\r\n  $__timeEpoch(C.DataHoraBateriaTestes),\r\n  0 as value,\r\n  'Sucesso' as metric\r\nFROM\r\n  WebServiceCheck C\r\nJOIN \r\n  Sistema S on S.Handle = C.HandleSistema\r\nJOIN \r\n  Ambiente A on A.Handle = C.HandleAmbiente\r\nWHERE\r\n  $__timeFilter(C.DataHoraBateriaTestes)\r\n  and S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\n  and C.Url is not null\r\n  and ISNULL(C.HttpStatusResposta, 0) != 200\r\nGROUP BY C.DataHoraBateriaTestes\r\n) x\r\nGROUP BY X.TIME, X.METRIC\r\nORDER BY\r\n  1 ASC"
    },
    {
     "rawSql": "SELECT \r\n  X.time,\r\n  SUM(X.value) AS VALUE,\r\n  x.metric\r\nfrom (\r\nSELECT\r\n  $__timeEpoch(C.DataHoraBateriaTestes),\r\n  count(1) as value,\r\n  'Erro' as metric\r\nFROM\r\n  WebServiceCheck C\r\nJOIN \r\n  Sistema S on S.Handle = C.HandleSistema\r\nJOIN \r\n  Ambiente A on A.Handle = C.HandleAmbiente  \r\nWHERE\r\n  $__timeFilter(C.DataHoraBateriaTestes)\r\n  and S.Nome = '$Sistema'  \r\n  and A.Nome = '$Ambiente'\r\n  and C.Url is not null\r\n  and ISNULL(C.HttpStatusResposta, 0) != 200\r\nGROUP BY C.DataHoraBateriaTestes\r\nUNION\r\nSELECT\r\n  $__timeEpoch(C.DataHoraBateriaTestes),\r\n  0 as value,\r\n  'Erro' as metric\r\nFROM\r\n  WebServiceCheck C\r\nJOIN \r\n  Sistema S on S.Handle = C.HandleSistema\r\nJOIN \r\n  Ambiente A on A.Handle = C.HandleAmbiente\r\nWHERE\r\n  $__timeFilter(C.DataHoraBateriaTestes)\r\n  and S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\n  and C.Url is not null\r\n  and (ISNULL(C.HttpStatusResposta, 0) = 200)\r\nGROUP BY C.DataHoraBateriaTestes\r\n) x\r\nGROUP BY X.time, X.metric\r\nORDER BY\r\n  1 ASC"
    },
    {
     "rawSql": "SELECT\r\n  $__timeEpoch(C.DataHoraBateriaTestes),\r\n  count(1) as value,\r\n  'Qtd Total' as metric\r\nFROM\r\n  WebServiceCheck C\r\nJOIN \r\n  Sistema S on S.Handle = C.HandleSistema\r\nJOIN \r\n  Ambiente A on A.Handle = C.HandleAmbiente  \r\nWHERE\r\n  $__timeFilter(C.DataHoraBateriaTestes)\r\n  and S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\n  and C.Url is not null\r\nGROUP BY C.DataHoraBateriaTestes\r\nORDER BY\r\n  1 ASC"
    }
   ]
  },
  {
   "title": "Tempo Médio Resposta do Ping (Geral)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Milissegundos" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch(H.DataHoraStatus),\n  H.TempoMediaResposta as value,\n  S.NOME as metric\nFROM\n  WebServiceHealth H\nJOIN \n  Sistema S on S.Handle = H.HandleSistema\nJOIN\n  Ambiente A on A.Handle = H.HandleAmbiente\nWHERE\n  $__timeFilter(H.DataHoraStatus) \n  and S.Nome = '$Sistema' \n  and A.Nome = '$Ambiente'\n  and H.Url is null\n  and H.TempoMediaResposta is not null\nORDER BY\n  H.DataHoraStatus ASC"
    }
   ]
  },
  {
   "title": "Exceções Ocorridas",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT distinct\r\n  C.NomeServicoIntegracao Servico,\r\n  C.Url,\r\n  C.TipoExcecao,\r\n  c.DetalhesExcecao,\r\n  count(1) AS Qtd\r\nFROM\r\n  WebServiceCheck C\r\nJOIN \r\n  Sistema S on S.Handle = C.HandleSistema\r\nJOIN\r\n  Ambiente A on A.Handle = C.HandleAmbiente  \r\nWHERE\r\n  $__timeFilter(C.DataHoraBateriaTestes) \r\n  and S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\n  and C.NomeServicoIntegracao is not null\r\n  and c.TipoExcecao is not null\r\ngroup by C.NomeServicoIntegracao,\r\n  C.Url,\r\n  C.TipoExcecao,\r\n  c.DetalhesExcecao\r\norder by C.NomeServicoIntegracao  "
    }
   ]
  },
  {
   "title": "URL dos Serviços",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT distinct\r\n  H.NomeServicoIntegracao Servico,\r\n  H.Url\r\nFROM\r\n  WebServiceHealth H\r\nJOIN \r\n  Sistema S on S.Handle = H.HandleSistema\r\nJOIN\r\n  Ambiente A on A.Handle = H.HandleAmbiente  \r\nWHERE\r\n  $__timeFilter(H.DataHoraStatus) \r\n  and S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\n  and H.NomeServicoIntegracao is not null\r\nORDER BY\r\n  H.NomeServicoIntegracao"
    }
   ]
  }
 ]
}