{
 "title": "Informações por Sistema",
 "tags": [ "informacoes" ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Ambiente", "query": "SELECT Nome FROM Ambiente" },
   {
    "name": "Sistema",
    "query": "SELECT S.NOME\nFROM SISTEMA S\nJOIN AMBIENTE A ON A.HANDLE  = S.HANDLEAMBIENTE\nWHERE A.NOME = '$Ambiente'"
   }
  ]
 },
 "panels": [
  {
   "title": "Versão Atual do Sistema",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT top 1 c.VersaoDoSistema\r\nFROM\r\n  InformacoesCheck C\r\nJOIN \r\n  Sistema S on S.Handle = C.HandleSistema\r\nJOIN\r\n  Ambiente A on A.Handle = C.HandleAmbiente  \r\nWHERE\r\n  S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\n  and C.Sucesso = 1\r\n  order by C.datahoraconsulta desc"
    }
   ]
  },
  {
   "title": "Versão DB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT top 1 c.VersaoDb\r\nFROM\r\n  InformacoesCheck C\r\nJOIN \r\n  Sistema S on S.Handle = C.HandleSistema\r\nJOIN\r\n  Ambiente A on A.Handle = C.HandleAmbiente  \r\nWHERE\r\n  S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\n  and C.Sucesso = 1\r\n  order by C.datahoraconsulta desc"
    }
   ]
  },
  {
   "title": "Última Correção",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT top 1 c.UltimaCorrecao\r\nFROM\r\n  InformacoesCheck C\r\nJOIN \r\n  Sistema S on S.Handle = C.HandleSistema\r\nJOIN\r\n  Ambiente A on A.Handle = C.HandleAmbiente  \r\nWHERE\r\n  S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\n  and C.Sucesso = 1\r\n  order by C.datahoraconsulta desc"
    }
   ]
  },
  {
   "title": "Última Alteração",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT top 1 c.UltimaAlteracao\r\nFROM\r\n  InformacoesCheck C\r\nJOIN \r\n  Sistema S on S.Handle = C.HandleSistema\r\nJOIN\r\n  Ambiente A on A.Handle = C.HandleAmbiente  \r\nWHERE\r\n  S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\n  and C.Sucesso = 1\r\n  order by C.datahoraconsulta desc"
    }
   ]
  },
  {
   "title": "Última Específica",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT top 1 c.UltimaEspecifica\r\nFROM\r\n  InformacoesCheck C\r\nJOIN \r\n  Sistema S on S.Handle = C.HandleSistema\r\nJOIN\r\n  Ambiente A on A.Handle = C.HandleAmbiente  \r\nWHERE\r\n  S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\n  and C.Sucesso = 1\r\n  order by C.datahoraconsulta desc"
    }
   ]
  },
  {
   "title": "Atualizações últimos 90 dias",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT c.DataHoraConsulta\r\n\t    ,c.NomeSistema    \r\n      ,c.BServerHost\r\n      ,c.BServerSistema\r\n      ,c.CustomSystem\r\n      ,c.EncryptVDb\r\n      ,c.LastOficial\r\n      ,c.NomeDoSistema\r\n      ,c.UltimaAlteracao\r\n      ,c.UltimaAlteracaoEncrypt\r\n      ,c.UltimaCorrecao\r\n      ,c.UltimaCorrecaoEncrypt\r\n      ,c.UltimaEspecifica\r\n      ,c.UltimaEspecificaEncrypt\r\n      ,c.UltimaParalela\r\n      ,c.UltimaParalelaEncrypt\r\n      ,c.VersaoDb\r\n      ,c.VersaoDoSistema\r\n      ,c.VerticalSystem\r\nFROM\r\n  InformacoesCheck C\r\nJOIN \r\n  Sistema S on S.Handle = C.HandleSistema\r\nJOIN\r\n  Ambiente A on A.Handle = C.HandleAmbiente  \r\nWHERE\r\n  C.DataHoraConsulta > (GETDATE()-90)\r\n  and S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\n  and C.Sucesso = 1\r\norder by C.DataHoraConsulta desc  "
    }
   ]
  },
  {
   "title": "Últimos 50 Erros na Consulta de informações",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT top 50 c.DataHoraConsulta\r\n\t    ,c.DataHoraRequisicao\r\n\t    ,c.DataHoraResposta\r\n\t    ,c.Mensagem\r\nFROM\r\n  InformacoesCheck C\r\nJOIN \r\n  Sistema S on S.Handle = C.HandleSistema\r\nJOIN\r\n  Ambiente A on A.Handle = C.HandleAmbiente  \r\nWHERE\r\n  C.DataHoraConsulta > (GETDATE()-90)\r\n  and S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\n  and C.Sucesso <> 1\r\norder by C.DataHoraConsulta desc  "
    }
   ]
  }
 ]
}