{
 "title": "Processos por Sistema",
 "tags": [ "processos" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Ambiente", "query": "SELECT Nome FROM Ambiente" },
   {
    "name": "Sistema",
    "query": "SELECT S.NOME\nFROM SISTEMA S\nJOIN AMBIENTE A ON A.HANDLE  = S.HANDLEAMBIENTE\nWHERE A.NOME = '$Ambiente'"
   }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DATEDIFF(second, '1970-01-01', getdate()) AS time,\r\n  sum(H.FinalizadosSucesso) + sum(H.FinalizadosErro) Total\r\nFROM\r\n  ProcessosCheck H\r\nJOIN \r\n  Sistema S on S.Handle = H.HandleSistema\r\nJOIN\r\n  Ambiente A on A.Handle = H.HandleAmbiente\r\nWHERE\r\n  $__timeFilter(H.DataHoraConsulta) \r\n  and Sucesso = 1\r\n  and S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Finalizados",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\r\n  DATEDIFF(second, '1970-01-01', getdate()) AS time,\r\n  sum(H.FinalizadosSucesso) FinalizadosSucesso,\r\n  sum(H.FinalizadosErro) FinalizadosErro\r\nFROM\r\n  ProcessosCheck H\r\nJOIN \r\n  Sistema S on S.Handle = H.HandleSistema\r\nJOIN\r\n  Ambiente A on A.Handle = H.HandleAmbiente\r\nWHERE\r\n  $__timeFilter(H.DataHoraConsulta) \r\n  and Sucesso = 1\r\n  and S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Executando",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DATEDIFF(second, '1970-01-01', getdate()) AS time,\r\n  max(H.ProcessosPendentes) MaximoProcessosPendentes,\r\n  max(H.ProcessosExecutando) MaximoProcessosExecutando\r\nFROM\r\n  ProcessosCheck H\r\nJOIN \r\n  Sistema S on S.Handle = H.HandleSistema\r\nJOIN\r\n  Ambiente A on A.Handle = H.HandleAmbiente\r\nWHERE\r\n  $__timeFilter(H.DataHoraConsulta) \r\n  and Sucesso = 1\r\n  and S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Processos",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeEpoch(H.DataHoraConsulta),\r\n  H.FinalizadosSucesso,\r\n  H.FinalizadosErro,\r\n  ProcessosPendentes,\r\n  ProcessosExecutando\r\nFROM\r\n  ProcessosCheck H\r\nJOIN \r\n  Sistema S on S.Handle = H.HandleSistema\r\nJOIN\r\n  Ambiente A on A.Handle = H.HandleAmbiente\r\nWHERE\r\n  $__timeFilter(H.DataHoraConsulta) \r\n  and Sucesso = 1\r\n  and S.Nome = '$Sistema' \r\n  and A.Nome = '$Ambiente'\r\nORDER BY\r\n  H.DataHoraConsulta ASC"
    }
   ]
  }
 ]
}